//Using try and catch in javascript
//A block of code that may cause an error is enclosed within a try statement.
try{
    console.log(a);
}catch{
    console.log("variable does't  exist");//variable does't  exist
}


// using take a variable 
let a =5;
try{
    console.log(a);
}catch{
    console.log("variable does't  exist");//5
}